Add field reporter to trait Verifier - adapting Carbon
viperproject/carbon pull request #383
Opened 2021-04-17 19:57 UTC by aterga

Should be merged after [Silver PR 513](https://github.com/viperproject/silver/pull/513).

2021-04-17 20:10 UTC, aterga commented
The new functionality is that ```BoogieInterface``` now reports ```BackendSubProcessReport``` messages to indicate at which communication stage with a Boogie process it's in. This is needed to make sure the IDE does not leak Z3 processes while used with Carbon. The problem is that Boogie sometimes terminates successfully while leaving its Z3 sub-process running. This occurs e.g. if there are matching loops in the SMT query. By the time the IDE decides to terminate a verification process (e.g. after a timeout) we can no longer find the PID of the leaked Z3 process as the parent Boogie process is already gone. We could collect the PIDs in advance, but for that we need to either poll (which is suboptimal) tr to know the moment in time when Carbon has already started a Boogie process. This is an example situation in which the client benefits from such reports.

2021-04-18 16:23 UTC, gauravpartha requested changes

2021-04-18 16:23 UTC, gauravpartha commented on src/main/scala/viper/carbon/CarbonVerifier.scala
> +
remove line

2021-04-18 16:23 UTC, gauravpartha commented on src/main/scala/viper/carbon/CarbonVerifier.scala
> -  def this() = this(Nil)
I guess def this() is never used?

2021-04-18 16:23 UTC, gauravpartha commented on src/main/scala/viper/carbon/verifier/BoogieInterface.scala
> +      reporter report BackendSubProcessReport("carbon", boogiePath, onOutput/*, _boogieProcessPid*/)
It's a bit strange that "onOutput" is lower case, while the other stages are upper case (such as "OnError"). But this is related to https://github.com/viperproject/silver/pull/513.

2021-04-18 16:24 UTC, gauravpartha commented
I guess the uncommented arguments ` _boogieProcessPid` are for https://github.com/viperproject/carbon/pull/384?

2021-05-15 14:24 UTC, aterga commented on src/main/scala/viper/carbon/CarbonVerifier.scala
> -  def this() = this(Nil)
Right, that's why I removed it.

2021-05-15 14:41 UTC, aterga commented
> I guess the uncommented arguments ` _boogieProcessPid` are for #384?

Exactly. 

Thanks for your review!

2021-05-15 16:28 UTC, aterga commented
No need to merge this. This PR has been incorporated into PR#384

2021-05-15 16:32 UTC, closed without merging