`asserting in`
viperproject/carbon pull request #455
Opened 2023-03-14 21:50 UTC by dewert99

Requires viperproject/silver#660
This is my attempt at adding supporting the `asserting in` feature in Carbon.
The "tests/all/asserting-in/wand.vpr" test from silver fails. Although, when I was initially working on this, this was also an issue when encoding `asserting in` using function preconditions, now the error seems specific to `asserting in`, so it may be worth looking into.

2023-03-15 00:44 UTC, alexanderjsummers requested changes
I think the pull request needs splitting into a silver one and a carbon one.

2023-03-15 00:44 UTC, alexanderjsummers commented on silver
I'm not sure how pull requests work across submodules; could this be a separate pull request for silver?

2023-03-15 00:44 UTC, alexanderjsummers commented on silver
In any case, github doesn't seem to understand how to present the diffs for these files.

2023-03-15 00:44 UTC, alexanderjsummers commented on src/main/scala/viper/carbon/modules/impls/DefaultExpModule.scala
> +      case h: sil.HintExp => translateExp(h.body)
This is nice to have. Is HintExp a sealed trait?

2023-03-16 16:19 UTC, dewert99 commented on silver
I did make two pull requests: see https://github.com/viperproject/silver/pull/660, this pull request references the silver commit in the silver pull request

2024-12-04 20:14 UTC, closed without merging

2024-12-04 20:14 UTC, jcp19 commented
I will close this, given that #531 was already merged.